import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Anafata Games | Maciej Skorus vs ImmutableX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <p className={styles.logo}><b>ImmutableX</b></p>
      </nav>

      <main className={styles.main}>
      <div className={styles.card}>
            <img src="https://card.godsunchained.com/?id=1382&q=4" className={styles.cardImg}></img>
            <div className={styles.cardDescription}>
              <p className={styles.desctiptionData}><b>Token address: </b>0xc9403243290483290489328409238094</p>
              <p className={styles.desctiptionData}><b>User: </b> Ja</p>
            </div>
          </div>
      </main>

    </div>
  )
}
