import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [data, setData] = useState([])

  useEffect(() => {
    const getData = () => {
      fetch("https://api.x.immutable.com/v1/assets?collection=0xacb3c6a43d15b907e8433077b6d38ae40936fe2c", {
        "method": "GET",
        "headers": {
          "Content-Type": "application/json"
        }
      })
      .then((res) => res.json())
      .then((res) => {
        setData(res.result)
      })
      .catch(err => {
        console.error(err)
      })
    }
    getData()
    console.log(data)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Anafata Games | Maciej Skorus vs ImmutableX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <p className={styles.logo}><b>ImmutableX</b></p>
      </nav>

      <main className={styles.main}>
      
        {data && data.map((item, index) => 
          <div key={index} className={styles.card}>
            <img src={item.image_url} alt={item.image_url} className={styles.cardImg}></img>
            <div className={styles.cardDescription}>
              <p className={styles.desctiptionData}><b>Token address: </b>{item.token_address}</p>
              <p className={styles.desctiptionData}><b>Token ID: </b>{item.token_id}</p>
              <p className={styles.desctiptionData}><b>User: </b>{item.token_id}</p>
              <p className={styles.desctiptionData}><b>Status: </b>{item.status}</p>
              <p className={styles.desctiptionData}><b>Name: </b>{item.name}</p>
              <p className={styles.desctiptionData}><b>Created at: </b>{item.created_at}</p>
              <p className={styles.desctiptionData}><b>Updated at: </b>{item.updated_at}</p>
            </div>
          </div>
        )}

      </main>

    </div>
  )
}
